### ISSUE TITLE
integrate fork into ansible-collection-ha

### ISSUE THREAD

**Issue by zerwes** [Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy#6]
as I am afraid #47 will die like #45, create a explicit fork of this repo with a note in the Readme (starting from the branch rls) and integrate it into [ansible-collection-ha](/evrardjp/ansible-collection-ha)
For my part, I use [keepalive role](/evrardjp/ansible-collection-ha/tree/main/roles/keepalived) mostly in combination with the haproxy role.

**Comment by evrardjp** [comment]
Thanks for considering this :)

**Comment by zerwes** [comment]
merged by @evrardjp (thx)

**Comment by evrardjp** [comment]
<img src="https://media0.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif"/>

Sorry for the slow response though!

**Comment by zerwes** [comment]
> Sorry for the slow response though!

no problem, lack of time is a well known problem to me too ...
